name = "ForecastVerification"
uuid = "fd2e94dc-1397-442f-9a83-1097d467d028"
authors = ["Alexander Barth <barth.alexander@gmail.com>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
